### ISSUE TITLE
Ampersands in Track or Album Names

### ISSUE THREAD

**Issue by johnstrr** [kentsangkm/clementine_spotify_search#2]
Ampersands in track or album names need to be encoded.  Sorry I don't know how to create a pull request, but I changed line 329 from
`song["name"],`
to
`song["name"].replace('&', '&amp;'),`

and similarly for line 333.

Thanks for providing this very useful script!

**Comment by kentsangkm** [comment]
Thx for reporting it.  Actually I found the issue couple months ago.. But as no one is using my script, I forgot to push.
Anyway, thx

**Comment by johnstrr** [comment]
I am using it all the time, and I am very grateful that you made it
available!  I don't know the best way to publicize it, but I imagine others
would appreciate it if they could find it.

Anyway, thank you!
Russell Johnston
